### PR TITLE
new spfx version

### PR DESCRIPTION
**Pull request by shurick81**

### CODE REVIEW

**Comment by shurick81** [comment]
@waldekmastykarz what do you think?

**Comment by waldekmastykarz** [comment]
Thanks for the reminder @shurick81! The PR looks good and I'll merge it including a release shortly 👍

**Comment by shurick81** [comment]
As soon this PR is merged, I'm ready to make another one with the latest SPFx version @waldekmastykarz :)

**Comment by waldekmastykarz** [comment]
Merged manually. Thank you! Releasing new image as we speak

**Pull request closed without merging**
