### PR TITLE
Feature/version match monitoring

### PR DESCRIPTION
**Pull request by shurick81**
An action that automatically fails when the version of spfx in npm is higher than the one pushed to the docker Hub. I tested it in another organization with actions enabled and it worked just fine, alerting on my email when the failure (mismatch) is detected. Related to #96

### CODE REVIEW

**Comment by waldekmastykarz** [comment]
Thanks! I thought that we wanted to make an action that creates an issue. If it just sends a failed notification and will do it daily, then it will require us to manually clean up the notification in the email, create an issue, stop the action, and restart it when we finish the work. It seems like it would create a bunch of extra effort, don't you think?

**Comment by shurick81** [comment]
We can do it weekly then? An email every week might be a good reminder.

**Comment by waldekmastykarz** [comment]
Personally, I'd prefer an issue in the repo. Because the amount of notifications, I ignore GitHub emails and use the notifications in the UI to see what requires my attention. Also, having an issue gives an opportunity for others to contribute rather than me having to create an issue first.

**Comment by shurick81** [comment]
I'd definitely prefer this too. Unfortunately, there seems no built in functionality for that in Github. However, we could use some open source one, like this: https://github.com/marketplace/actions/create-an-issue. We will need to feed it some GitHub token, I hope you are alright with that @waldekmastykarz

**Comment by waldekmastykarz** [comment]
We can absolutely create a secret that allows us to create an issue from an action.

To recap, the action should:

- check for a new SPFx release
- if there's a new SPFx release, check if there's an issue for it already
- if there's no issue for it, create an issue

**Comment by waldekmastykarz** [comment]
Closing due to inactivity

**Pull request closed without merging**
